var autores_igp = [
"Adv\u00EDnculaZeballos,Orlando",
"Aguilar,V.",
"Aguilar,Victor",
"Aguilar,V\u00EDctor",
"Agu\u00EDlar,V\u00EDctor",
"Agüero,Consuelo",
"AliMurillo,Armando",
"Ali,L.",
"Alvarado,W.",
"AlvarezTolentino,Daniel",
"AmpueroGr\u00E1ndez,Angela",
"Anca,J.",
"AncassiFigueroa,RosaMar\u00EDa",
"Ancassi,Rosa",
"Anccasi,Rosa",
"AnicamaD\u00EDaz,Jahir",
"AntayhuaVera,YanetTeresa",
"Antayhua,Y.",
"Antayhua,Yanet",
"Apaestegui,J.",
"AparcoLara,Jonathan",
"Aparco,Jonathan",
"Apa\u00E9steguiCampos,JamesEmiliano",
"Apa\u00E9stegui,J.",
"Apa\u00E9stegui,James",
"ArguedasMadrid,C\u00E9sar",
"Arguedas,C\u00E9sar",
"ArmijosCardenas,Elisa",
"Armijos,Elisa",
"ArredondoGarc\u00EDa,LuzMercedes",
"Arredondo,Luz",
"ArroyoAliaga,Jacinto",
"Arroyo,Jacinto",
"Arteaga,Jaime",
"Audin,L.",
"Audin,Laurence",
"AzabacheCobe\u00F1a,Jos\u00E9Manuel",
"A\u00F1azcoCondori,Martha",
"A\u00F1azco,Martha",
"Baella,N.O.",
"Baella,Nobar",
"BejaranoPinto,LisbethEliana",
"BernalEsquia,Isabel",
"BernalEsquia,YeseniaIsabel",
"Bernal,I.",
"Bernal,Isabel",
"Bondoux,F.",
"Bondoux,Francis",
"BustamanteHuam\u00E1n,YonatanAnibal",
"BustamanteValencia,MarcosRenzo",
"Cabezas,DenisP.",
"CahuariBegazo,Ang\u00E9licaYsabel",
"Cahuari,Ang\u00E9lica",
"Calla\u00F1aupaGutierrez,StephanyMagaly",
"Campos,Fernando",
"CampoverdeOropeza,Jos\u00E9Mar\u00EDa",
"Carpio,Julia",
"CarrilloElizalde,RobertPaul",
"CarrilloElizalde,RoberthPa\u00FAl",
"Carrillo,Robert",
"Castillo,Cristiam",
"Castillo,Cristiam.",
"CastroMendoza,Rub\u00E9n",
"CcalloHuaquisto,Freddy",
"CcalloHuaquisto,FreddyJavier",
"Cccallo,Freddy",
"CentenoMoncada,EstelaJuana",
"CentenoQuico,Riky",
"Centeno,Ricky",
"Centeno,Riky",
"ChahuaJanampa,JhonElvis",
"Chahua,Jhon",
"ChangHuayanca,AntonioJos\u00E9",
"Charapaqui,Saul",
"Charapaqui,Sa\u00FAl",
"ChauChongShing,JorgeLuis",
"Chavez,R.",
"Chavez,StevenP.",
"Chijcheapaza,R.",
"Chijcheapaza,R.",
"Chijcheapaza,Rolando",
"Chijcheapaza,Rolando",
"Chire-Chira,J.",
"ChiroqueHerrera,CristhianAnderson",
"Chiroque,Cristhian",
"Chlie,M.",
"Chlieh,M.",
"Chlieh,Mohamed",
"Choque,Edwin",
"Ch\u00E1vezJara,StevenPaul",
"Ch\u00E1vez,Ra\u00FAl",
"Ch\u00E1vez,Steven",
"ConchaCalle,JorgeAndr\u00E9s",
"Concha,Jorge",
"CondoriQuispe,Cristobal",
"Condori,Cristobal",
"Condori,Crist\u00F3bal",
"CruzIdme,John",
"CruzIgme,JohnEdward",
"Cruz,John",
"Cruz,Nicolas",
"Cruz,V.",
"Cruz,Vicentina",
"CutipaVargas,GracianoElard",
"Cutipa,Elard",
"CuyaCrispin,\u00C1ngelAdemir",
"Cuya,Ademir",
"C\u00E9spedesReyes,Luis",
"C\u00E9spedes,Luis",
"DeLaJara,Cesar",
"DelaJara,C.",
"DelaJara,C\u00E9sar",
"DelCarpioCalienes,Jos\u00E9",
"DelCarpio,J.",
"DelCarpio,Jose",
"DelCarpio,Jos\u00E9",
"DelCarpio,Jos\u00E9Alberto",
"DelCarpio,Jos\u00E9Luis",
"DelCastilloVarlarde,Carlos",
"Delgado,Mar\u00EDa",
"Dewitte,B.",
"Dewitte,Boris",
"Direcci\u00F3ndeGeof\u00EDsica&Sociedad",
"Direcci\u00F3ndeGeof\u00EDsica&Sociedad.",
"Due\u00F1asGald\u00F3s,Rub\u00E9nDario",
"EncisoCondorcuya,Lidia",
"Enciso,Carlos",
"Enciso,Lidia",
"EspinozaVillar,JhanCarlo",
"Espinoza,J.",
"Espinoza,J.C.",
"Espinoza,J.C.",
"Espinoza,J.C.V.",
"Espinoza,JhanCarlo",
"Espinoza,Jhan-Carlo",
"Espinoza-Villar,Raul",
"EspinozaVillar,Ra\u00FAlArnaldo",
"Estevan,Ren\u00E9",
"FajardoUrbina,JeancarloManuel",
"Fajardo,Jeancarlo",
"Feijo\u00F3Fox,EduardAlder",
"Fern\u00E1ndez,Efrain",
"Fern\u00E1ndez,Efra\u00EDn",
"Florentino,Andre",
"Florentino,Andr\u00E9",
"Florentino,Andr\u00E9.",
"FloresGuerra,EddenChristian",
"FloresRojas,Jos\u00E9Luis",
"Flores,Andr\u00E9s",
"Flores,Antonio",
"Flores,Cristhian",
"Flores,Daniel",
"Flores,Jos\u00E9L.",
"GaldosSegura,Andre\u00E9William",
"Gald\u00F3s,Andre\u00E9",
"Gald\u00F3s,Andr\u00E9",
"Gald\u00F3s,Andr\u00E9s",
"Garc\u00EDaRosales,AlanJes\u00FAs",
"Geof\u00EDsica&Sociedad",
"Geof\u00EDsica&Sociedad.",
"Gilt,Huber",
"Gir\u00E1ldez,Lucy",
"GonzalesZenteno,Edgar",
"GonzalesZenteno,HermogenesEdgard",
"GonzalesZu\u00F1iga,K.",
"Gonzales,Katherine",
"Goubanova,K.",
"Goubanova,Katerina",
"Goubanova,Katherine",
"GoyburoPe\u00F1a,Andres",
"GuardiaAnampa,PatriciaAlejandra",
"Guardia,Patricia",
"Gutierrez-Cori,Omar",
"Gutierrez‐Cori,Omar",
"Guzm\u00E1nMendivil,Jos\u00E9Luis",
"G\u00F3mezAvalos,JuanCarlos",
"G\u00F3mez,Andr\u00E9s",
"G\u00F3mez,JuanCarlos",
"HerasMuchica,Hern\u00E1nLucas",
"Heras,Hern\u00E1n",
"HerreraPuma,DinaBilha",
"Herrera,Bilha",
"Huaco,Daniel",
"Huaman,Darwin",
"Huaman,J",
"Huaman-Rodrigo,David",
"Huam\u00E1nChuquihuaccha,Lidia",
"Huam\u00E1n,L.",
"Huam\u00E1n,Lidia",
"Huam\u00E1n,Mar\u00EDa",
"Huam\u00E1n-Rodrigo,D.",
"Huam\u00E1n-Rodrigo,David",
"Huancco,Orlando",
"Illig,S.",
"Illig,Selena",
"Illig,Serena",
"Illig,S\u00E9r\u00E9na",
"Ingunza,Augusto",
"InzaCallupe,LambertoAdolfo",
"Inza,A.",
"Inza,Adolfo",
"Inza,L.A.",
"Ishitsuka,J.",
"Ishitsuka,Jos\u00E9",
"Ishitsuka,Jos\u00E9K.",
"Ishitsuka,Mutsumi",
"Jauregui,YakeliynR.",
"Jimenez,C.",
"Jimenez,C\u00E9sar",
"Junquas,C.",
"Junquas,Cl\u00E9mentine",
"Kumar,Shailendra",
"LagosEnriquez,Pablo",
"LagosEnr\u00EDquez,Pablo",
"Lagos,P.",
"Lagos,Pablo",
"LatinezSotomayor,KarenA.",
"Lat\u00EDnezSotomayor,KarenAlexandra",
"Lavado,Hector",
"Lavado,H\u00E9ctor",
"Leucci,Cristiana",
"Le\u00F3nAltuna,KarenBeatriz",
"Le\u00F3nAltuna,KarenBeatriz",
"Le\u00F3n,Karen",
"Le\u00F3n,Karen",
"Limachi,Nancy",
"MacedoFranco,Luisa,Diomira",
"MacedoS\u00E1nchez,Orlando",
"MacedoS\u00E1nchez,OrlandoEfra\u00EDn",
"Macedo,L.",
"Macedo,O.",
"Macedo,Orlando",
"Machaca,Roger",
"Machacca,Roger",
"MachucaBre\u00F1a,RicardoOswaldo",
"Malpartida,Alan",
"MamaniGonzales,DalmaMercedes",
"MamaniMarca,GumercindoWilson",
"Manrique,Mar\u00EDa",
"Mari\u00F1oSalazar,Jersy",
"Mari\u00F1o,J.",
"MartinezGrimaldo,Alejandra",
"Mart\u00EDnezCastro,Daniel",
"Mart\u00EDnezGrimaldo,Alejandra",
"Mart\u00EDnezGrimaldo,AlejandraG.",
"Mart\u00EDnezHerrera,JulioC\u00E9sar",
"Mart\u00EDnez,A.G.",
"Mart\u00EDnez,Alejandra",
"Mart\u00EDnez,Daniel",
"Mart\u00EDnez,Julio",
"Mart\u00EDnez-Castro,D.",
"Mart\u00EDnez-Castro,Daniel",
"Mar\u00EDn,Gloria",
"MedinaB.,Melissa",
"MedinaSamanez,CristopherJes\u00FAs",
"Medina,Melissa",
"Milla,M.",
"Milla,M.A.",
"Milla,Marco",
"Milla,MarcoA.",
"Milla,Marco.",
"Millones,Jos\u00E9",
"MinayaLiz\u00E1rraga,Armando",
"Minaya,Armando",
"Molina,Javier",
"Mollo,Mary",
"MonccaAnculle,Gerem\u00EDas",
"Moncca,Geremias",
"MontesTorres,Ivonne",
"MontesTorres,Yvonne",
"Montes,Ivonne",
"Montes,Yvonne",
"Montes,Yvonne",
"Montesinos,V\u00EDctor",
"Moquet,J.S.",
"Moquet,JeanS\u00E9bastien",
"Moquet,Jean-Sebastien",
"Moquet,Jean-S\u00E9bastien",
"Moquet,Jean‐S\u00E9bastien",
"Moreno,Marco",
"MoreraJulca,SergioByron",
"Morera,S.B.",
"Morera,Sergio",
"Morera,SergioB.",
"Morera-Julca,Sergio",
"Mor\u00F3n,Katherine",
"MosqueraV\u00E1squez,KobiAlberto",
"MosqueraV\u00E1squez,Koby",
"MosqueraV\u00E1squez,KobyAlberto",
"Mosquera,K.",
"Mosquera,Kobi",
"Mosquera,Koby",
"Mosquera-V\u00E1squez,K.",
"Mosquera-V\u00E1squez,Kobi",
"Mosquera‐V\u00E1squez,K.",
"Moya,AldoS.",
"Moya-\u00C1lvarez,AldoS.",
"Moya\u00C1lvarez,AldoSaturnino",
"NinaFigueroa,Vilma",
"NorabuenaOrtiz,Edmundo",
"Norabuena,E.",
"Norabuena,Edmundo",
"Norabuena,EdmundoO.",
"OchoaZamalloa,\u00C1ngelJair",
"Ochoa,Angel",
"OcolaAquise,Leonidas",
"Ocola,Leonidas",
"Ord\u00F3\u00F1ezPiscoya,JorgeArmando",
"Ord\u00F3\u00F1ez,Jorge",
"OrihuelaPinto,LuisBryam",
"Orihuela,Bryam",
"OrtizV\u00E1squez,Rub\u00E9nOmar",
"Ortiz,Segundo",
"Oscanoa,Julio",
"Oyola,Javier",
"PacciniPe\u00F1a,LauraGiulianna",
"Paccini,Laura",
"Pacheco,E.",
"Pacheco,Edgar",
"Pacheco,Edgardo",
"Pacheco,EdgardoE.",
"Pareja,David",
"PariRendon,KellyAmanda",
"Parillo,Rocio",
"ParraPait\u00E1n,ClaudiaCarolina",
"Pereyra,A.",
"Pereyra,Antonio",
"Perfettini,H.",
"Perfettini,Hugo",
"PintoCh\u00E1vez,GiselaKatherine",
"Portugal,David",
"PradoMendoza,Mar\u00EDaRoxana",
"Prieto,Eva",
"Pr\u00EDncipeAguirre,RomelErick",
"Pr\u00EDncipe,Erick",
"PumaSacsi,Nino",
"Puma,N.",
"Puma,Nino",
"P\u00E9rezAlvarado,Susan",
"P\u00E9rezSegovia,Alexander",
"P\u00E9rezSegovia,Alexander",
"P\u00E9rez,Alexander",
"P\u00E9rez-Pacheco,Ivonne",
"QuijanoVargas,JulioJes\u00FAs",
"QuinchoOlaz\u00E1bal,JanetBr\u00EDgida",
"Quispe,Rodrigo",
"RamosChura,SoniaEstephanie",
"RamosJauregui,LuceroYakelyn",
"RamosPalomino,DomingoA.",
"Ramos,D.",
"Ramos,Domingo",
"Ramos,Yakelyn",
"Ram\u00EDrezCh\u00E1vez,DiegoRenzo",
"Ra\u00FAlEspinoza,Villar",
"ReupoV\u00E9lez,JorgeAntonio",
"Reupo,Jorge",
"Rivera,Gerardo",
"Rivera,Marco",
"Rivera,Marcos",
"Rodriguez,Sime\u00F3n",
"Rodr\u00EDguezV.,Leandro",
"Rodr\u00EDguez,Leandro",
"Rodr\u00EDguez,Sime\u00F3n",
"RojasVillalba,EnriqueLuisAlfonso",
"RosalesCorilloclla,Domingo",
"Rosales,D.",
"Rosales,Domingo",
"SaavedraHuanca,Miguel",
"Saavedra,M.",
"Saavedra,Miguel",
"Salas,Henry",
"Santill\u00E1n,Oscar",
"SantosChaparro,Luis",
"Santos,Luis",
"Scipion,D.L.",
"Scipion,Danny",
"Scipi\u00F3n,D.",
"Scipi\u00F3n,D.E.",
"Scipi\u00F3n,Danny",
"Scipi\u00F3n,DannyE.",
"Scipi\u00F3n,Danny.",
"SeguraCajachagua,HansMikhail",
"SeguraCuri,Berl\u00EDnAveles",
"Segura,B.",
"Segura,Berlin",
"Segura,Berl\u00EDn",
"Segura,H.",
"Segura,Hans",
"SilvaVidal,Yamina",
"Silva,Y.",
"Silva,Yamina",
"Silva,Yamina",
"Silva-Vidal,Y.",
"SolesValdivia,AnaMar\u00EDa",
"Suarez-Salas,Luis",
"SulcaJota,JuanCarlos",
"Sulca,Juan",
"SullaHuillca,Wilfredo",
"Sulla,Wilfredo",
"Suni,Jaime",
"Su\u00E1rezSalas,Luis",
"Su\u00E1rez-Salas,Luis",
"S\u00E1nchez,B.",
"S\u00E1nchez-Ccoyllo,Od\u00F3nR.",
"Taipe,E.",
"Taipe,Edu",
"TakahashiGuevara,Ken",
"Takahashi,K.",
"Takahashi,Ken",
"TaveraHuarache,Hernando",
"Tavera,H.",
"Tavera,Hernando",
"Tavera,HernandoJ.",
"Thual,Sulian",
"Thual,Sullian",
"TicseDelaTorre,KaterineElsy",
"TorresAguilar,Jos\u00E9",
"TorresVelarde,LilianaRosario",
"Torres,Jos\u00E9",
"Torres,Jos\u00E9Luis",
"Torres,Liliana",
"TrasmonteSoto,Grace",
"TrasmonteSoto,GraceLiliam",
"Trasmonte,G.",
"Trasmonte,Grace",
"ValdiviaPolanco,IgorAlberto",
"ValdiviaPrado,JairoMichael",
"Valdivia,Igor",
"VargasAlva,Katherine",
"VargasAlva,KatherineAndrea",
"Vargas,K.",
"VelardeQuispe,Lizbeth",
"Velarde,L.",
"Velarde,Lizbeth",
"VelizC.,O.",
"Veliz,O.",
"Veliz,O.E.",
"Veliz,Oscar",
"VidalSafor,Erick",
"Vidal,E.",
"VilaMamani,KatiaVeronica",
"Vilca,J.",
"Vilca,Javier",
"Vilca,Renzo",
"Vilcapoma,L.",
"Vilcapoma,Luis",
"Villafani,Rub\u00E9n",
"VillalobosPuma,ElverEdmundo",
"Villalobos,Elver",
"Villar,Ra\u00FAl",
"VillaverdeCalder\u00F3n,Marita",
"VillaverdeCalder\u00F3n,Mar\u00EDa",
"Villaverde,Mar\u00EDa",
"VillegasLanza,J.C.",
"VillegasLanza,JuanCarlos",
"Villegas,JuanCarlos",
"Villegas-Lanza,J.",
"Villegas-Lanza,J.-C.",
"Villegas-Lanza,J.C.",
"Villegas‐Lanza,J.C.",
"VivancoL\u00F3pez,SocorrodelPilar",
"VizcarraZ\u00FA\u00F1iga,MiriamEliana",
"WoodmanP.,Ronald",
"WoodmanP.,RonaldF.",
"WoodmanPollitt,Ronald",
"WoodmanPollitt,RonaldFrancisco",
"Woodman,D.",
"Woodman,R",
"Woodman,R.",
"Woodman,R.F",
"Woodman,R.F.",
"Woodman,R.F",
"Woodman,R.F.",
"Woodman,Ronald",
"Woodman,RonaldF.",
"YauriCondo,S.",
"YauriCondo,SheilaAlodia",
"Yauri,Sheila",
"Zamudio,Yolanda",
"ZubietaBarrag\u00E1n,Ricardo",
"Zubieta,R.",
"Zubieta,Ricardo",
"\u00C1lvarez,Yovana"
];

$( document ).ready(function() {
    $('select[name="year_filter"]').change(function(){
        $(this).parents('form:first').submit();
    });
    $('select[name="semester_filter"]').change(function(){
        $(this).parents('form:first').submit();
    });
    
    if($('#aspect_statistics_PublicacionesIndexTransformer_table_tabla-comunidades-pubindx').length != 0){
        var aux_name =$('#aspect_statistics_PublicacionesIndexTransformer_table_tabla-comunidades-pubindx .ds-table-row td:nth-child(3)');
        var aux_valor =$('#aspect_statistics_PublicacionesIndexTransformer_table_tabla-comunidades-pubindx .ds-table-row td:nth-child(4)');
        var data_comunidad_pub=[];
        var total_pubs = 0;
        for (let i = 0; i < aux_name.length; i++) {
                data_comunidad_pub[i] = {'name': aux_name[i].innerHTML , 'y': aux_valor[i].innerHTML*1, 'drilldown': null}
                total_pubs += aux_valor[i].innerHTML*1;			
        }
        //console.log(total_pubs);
      charge_chart_bar_drilldown($('#aspect_statistics_PublicacionesIndexTransformer_div_publicaciones-indexadas h2')[2].innerHTML,
                ($('#aspect_statistics_PublicacionesIndexTransformer_div_comunidades-pubindx h3')[0].innerHTML)+' '+($('#aspect_statistics_PublicacionesIndexTransformer_div_total-pubindx p')[0].innerHTML), 
                'aspect_statistics_PublicacionesIndexTransformer_div_comunidades-pubindx', 
                $('#aspect_statistics_PublicacionesIndexTransformer_table_tabla-comunidades-pubindx th:nth-child(4)')[0].innerHTML, 
                'Comunidad', 
                data_comunidad_pub, 
                []);
    }
    if($('#aspect_statistics_PublicacionesIndexTransformer_table_tabla-publicaciones-indexadas').length != 0){
        var element_autores =$('#aspect_statistics_PublicacionesIndexTransformer_table_tabla-publicaciones-indexadas .ds-table-row td:nth-child(3)');	
        var uri =$('#aspect_statistics_PublicacionesIndexTransformer_table_tabla-publicaciones-indexadas .ds-table-row td:last-child()');
        var titulo = $('#aspect_statistics_PublicacionesIndexTransformer_table_tabla-publicaciones-indexadas .ds-table-row td:nth-child(2)');
        
	//console.log(titulo);
	for ( var h = 0; h < uri.length; h++ ){
		titulo[h].innerHTML = '<a class="" href="' + uri[h].innerHTML + '">' + titulo[h].innerHTML + '</a>';
		uri[h].remove();
	}
	$('#aspect_statistics_PublicacionesIndexTransformer_table_tabla-publicaciones-indexadas th:last-child()').remove();
        for (let i = 0; i < element_autores.length; i++) {
         //console.log(element_autores[i].innerHTML.split(';'));
         let aux_autores = element_autores[i].innerHTML.split(';');
         	element_autores[i].innerHTML = '';

        	for (let j = 0; j < aux_autores.length-1; j++) {
        		aux_autores[j] = aux_autores[j].trim();
        		//aux_autores[j] = aux_autores[j].replace(/\s/g, '');        		
        		if(isIGPauthor(aux_autores[j].replace(/\s/g, ''))){
        			//console.log(aux_autores[j]);    
        			aux_autores [j] = '<label class="autor autorIGP">'+aux_autores [j]+'</label>'
        		}else{
        			aux_autores [j] = '<label class="autor">'+aux_autores [j]+'</label>'	
        		}
        		element_autores[i].innerHTML += aux_autores [j] ;
        		if(!(j===(aux_autores.length)-2)){
        			element_autores[i].innerHTML +='<label class="separator-autor">;</label>';
        		}        		
        	}
        }
    }
   
    $('<p class="mensaje"><span class="red-text">*</span> Los autores que se encuentran de color <span class="red-text">rojo</span> indican que son investigadores del IGP.</p><span class="" style="font-weight: bold;">'+ total_pubs +' publicaciones</span>').insertAfter($('#aspect_statistics_PublicacionesIndexTransformer_div_publicaciones-indexadas h2')[3]);
});

function isIGPauthor(autor){
	var is = false;
	var i=0;
	while(!is && i < autores_igp.length){
		if(autor.toLowerCase() === autores_igp[i].toLowerCase()){
			is=true;
		}
		i++;
	}
	return is;
}

function charge_chart_bar_drilldown(title, subtitle, container, textyAxis, nameSerie, data_comunidad, data_drilldown){
// Create the chart
	Highcharts.chart(container, {
	  chart: {
	    type: 'column'
	  },
	  title: {
	    text: title
	  },
	  subtitle: {
	    text: subtitle
	  },
	  xAxis: {
	    type: 'category'
	  },
	  yAxis: {
	    title: {
	      text: textyAxis
	    }
	  },
	  legend: {
	    enabled: false
	  },
	  plotOptions: {
	    series: {
	      borderWidth: 0,
	      dataLabels: {
	        enabled: true,
	        format: '{point.y:1f}'
	      }
	    }
	  },

	  tooltip: {
	    headerFormat: '<span style="font-size:11px"><b>{series.name}</b></span><br>',
	    pointFormat: '<b><span style="color:{point.color}">{point.name}</span></b>: <b>{point.y:2f}</b> publicaciones<br/>'
	  },

	  "series": [
	    {
	      "name": nameSerie,
	      "colorByPoint": true,
	      "data": data_comunidad
	    }
	  ],
	  "drilldown": {
	    "series": data_drilldown
	  }
	});

}
